version: '3'

services:

  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: video-streaming-api
      MYSQL_PASSWORD: passvsa123
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "false"
      MYSQL_SSL: "false"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - migration

  flyway:
    image: flyway/flyway
    container_name: flyway
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/video-streaming-api?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: root
      FLYWAY_PASSWORD: pass123
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "false"
      MYSQL_SSL: "false"
    command: migrate
    depends_on:
      - mysql
    networks:
      - migration

volumes:
  mysql-data:

networks:
  migration: